/**
 * Store data for the LaMa / Quick Track locator.
 *
 * PROVENANCE — read before trusting any field.
 * Recovered 2026-08-22 from a Wayback snapshot (2023-03-26) of
 * quicktrackinc.com/visit-us, parsed out of the wp-google-map-plugin
 * `places[]` payload. Phones came separately from archived per-store pages.
 *
 * VERIFIED-REAL     name, address, city, state, zip, lat, lng, category
 * PLACEHOLDER       hours  — every row says "Call to confirm". No hours exist
 *                   in ANY recovered source. Do NOT invent them; wrong hours
 *                   are worse than absent hours.
 * PARTIAL           phone  — 8 of 96 recovered. The rest are empty strings.
 *
 * The snapshot is ~2.5 years old. Stores open and close. Treat every row as
 * needing confirmation before it is used for anything consequential.
 *
 * TO REPLACE WITH REAL DATA: export the 96 listings from the Google Business
 * Profile account (authoritative, and you own them), or use the Places API.
 * Google search results are JS-gated and scraping them breaks their ToS, so
 * that is not a route. See PLACEHOLDERS.md.
 */

export interface Store {
  id: number;
  name: string;
  /** Full single-line address. Real, from the recovered data. */
  address: string;
  lat: number;
  lng: number;
  /** Empty string when not recovered. 8 of 96 are real. */
  phone: string;
  /** "Call to confirm" on every row — see hoursVerified. Never invented. */
  hours: string;
  city?: string;
  state?: string;
  zip?: string;
  /** Source categories: "c-store + gas", "c-store", "Fuel", "qt store", etc. */
  category?: string;
  /** False on every row today. Flip per-store as hours are confirmed. */
  hoursVerified?: boolean;
  phoneVerified?: boolean;
  /** False when the source had no street number - 6 of 96 today. */
  addressComplete?: boolean;
}

export const stores: Store[] = [
  {
    id: 1,
    name: 'Lincoln Grocery',
    address: '1701 Lincoln Ave, Fort Worth',
    lat: 32.77855,
    lng: -97.35647,
    phone: '',
    hours: 'Call to confirm',
    city: 'Fort Worth',
    state: '',
    zip: '',
    category: 'c-store',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 2,
    name: 'Quick Track Fuel',
    address: 'Arkansas',
    lat: 35.20105,
    lng: -91.8318334,
    phone: '',
    hours: 'Call to confirm',
    city: '',
    state: 'AR',
    zip: '',
    category: 'Fuel',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: false,
  },
  {
    id: 3,
    name: 'Quick Track 51',
    address: '504 Front Street, Dierks, AR, 71833',
    lat: 34.11666,
    lng: -94.02271,
    phone: '870-286-2911',
    hours: 'Call to confirm',
    city: 'Dierks',
    state: 'AR',
    zip: '71833',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 4,
    name: 'Quick Track Fuel',
    address: 'Louisiana, LA',
    lat: 30.9842977,
    lng: -91.96233269999999,
    phone: '',
    hours: 'Call to confirm',
    city: '',
    state: 'LA',
    zip: '',
    category: 'Fuel',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: false,
  },
  {
    id: 5,
    name: 'Quick Track Fuel',
    address: 'Mississippi, MS',
    lat: 32.3546679,
    lng: -89.3985283,
    phone: '',
    hours: 'Call to confirm',
    city: '',
    state: 'MS',
    zip: '',
    category: 'Fuel',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: false,
  },
  {
    id: 6,
    name: 'Quick Track Fuel',
    address: 'New Mexico, NM',
    lat: 34.5199402,
    lng: -105.8700901,
    phone: '',
    hours: 'Call to confirm',
    city: '',
    state: 'NM',
    zip: '',
    category: 'Fuel',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: false,
  },
  {
    id: 7,
    name: 'Quick Track 84',
    address: '1801 San Pedro Dr. NE, Albuquerque, NM, 87110',
    lat: 35.09497,
    lng: -106.57794,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87110',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 8,
    name: 'Quick Track 85',
    address: '1720 Central SE, Albuquerque, NM, 87106',
    lat: 35.08097,
    lng: -106.62718,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87106',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 9,
    name: 'Quick Track 86',
    address: '400 Cooper NW, Albuquerque, NM, 87102',
    lat: 35.08569,
    lng: -106.6523,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87102',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 10,
    name: 'Quick Track 87',
    address: '10320 Candaleria Rd. ME, Albuquerque, NM, 87112',
    lat: 35.11579,
    lng: -106.52486,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87112',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 11,
    name: 'Quick Track 88',
    address: '12000 Menaul NE, Albuquerque, NM, 87123',
    lat: 35.10841,
    lng: -106.50617,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87123',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 12,
    name: 'Quick Track 89',
    address: '12524 Central SE, Albuquerque, NM, 87123',
    lat: 35.06928,
    lng: -106.51005,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87123',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 13,
    name: 'Quick Track 90',
    address: '1800 Lomas Blvd NE, Albuquerque, NM, 87106',
    lat: 35.08925,
    lng: -106.62381,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87106',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 14,
    name: 'Quick Track 92',
    address: '1401 Wyoming Blvd NE, Albuquerque, NM, 87112',
    lat: 35.09482,
    lng: -106.55111,
    phone: '',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87112',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 15,
    name: 'Quick Track 93',
    address: '2625 Wyoming Blvd NE, Albuquerque, NM, 87110',
    lat: 35.13431,
    lng: -106.55111,
    phone: '505-292-6586',
    hours: 'Call to confirm',
    city: 'Albuquerque',
    state: 'NM',
    zip: '87110',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 16,
    name: 'Quick Track Fuel',
    address: 'Oklahoma',
    lat: 35.0077519,
    lng: -97.092877,
    phone: '',
    hours: 'Call to confirm',
    city: '',
    state: 'OK',
    zip: '',
    category: 'Fuel',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: false,
  },
  {
    id: 17,
    name: 'Quick Track Fuel',
    address: 'Texas, TX',
    lat: 32.331958470627896,
    lng: -100.61776156066489,
    phone: '',
    hours: 'Call to confirm',
    city: '',
    state: 'TX',
    zip: '',
    category: 'Fuel',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: false,
  },
  {
    id: 18,
    name: 'Quick Track 29',
    address: '5101 Little Rd, Arlington, TX, 76017',
    lat: 32.664393,
    lng: -97.206364,
    phone: '',
    hours: 'Call to confirm',
    city: 'Arlington',
    state: 'TX',
    zip: '76017',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 19,
    name: 'Quick Track 3',
    address: '1506 W. Mayfield Rd., Arlington, TX, 76015',
    lat: 32.692097,
    lng: -97.132168,
    phone: '',
    hours: 'Call to confirm',
    city: 'Arlington',
    state: 'TX',
    zip: '76015',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 20,
    name: 'Quick Track 20',
    address: '510 S. Palestine, Athens, TX, 75751',
    lat: 32.196788,
    lng: -95.853877,
    phone: '',
    hours: 'Call to confirm',
    city: 'Athens',
    state: 'TX',
    zip: '75751',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 21,
    name: 'Quick Track 43',
    address: '85 E Hwy 155, Avinger, TX, 75630',
    lat: 32.892477,
    lng: -94.565204,
    phone: '',
    hours: 'Call to confirm',
    city: 'Avinger',
    state: 'TX',
    zip: '75630',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 22,
    name: 'Quick Track 10',
    address: '1501 E Pipeline Rd, Bedford, TX, 76022',
    lat: 32.82272,
    lng: -97.14233,
    phone: '',
    hours: 'Call to confirm',
    city: 'Bedford',
    state: 'TX',
    zip: '76022',
    category: 'c-store',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 23,
    name: 'Quick Track 13',
    address: '1501 E. Pipeline Road,Bedford, TX, 76022',
    lat: 32.822765,
    lng: -97.142426,
    phone: '',
    hours: 'Call to confirm',
    city: 'Bedford',
    state: 'TX',
    zip: '76022',
    category: 'qt store',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 24,
    name: 'Quick Track 2',
    address: '401 E. Pipeline Road, Bedford, TX, 76022',
    lat: 32.823901,
    lng: -97.159447,
    phone: '817-282-9496',
    hours: 'Call to confirm',
    city: 'Bedford',
    state: 'TX',
    zip: '76022',
    category: 'c-store',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 25,
    name: 'Quick Track 83',
    address: '300 Ownes St., Bigspring, TX, 79720',
    lat: 32.25525,
    lng: -101.46926,
    phone: '',
    hours: 'Call to confirm',
    city: 'Bigspring',
    state: 'TX',
    zip: '79720',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 26,
    name: 'Quick Track 18',
    address: '105 Broadway, Bogata, TX, 75417',
    lat: 33.469685,
    lng: -95.213554,
    phone: '',
    hours: 'Call to confirm',
    city: 'Bogata',
    state: 'TX',
    zip: '75417',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 27,
    name: 'Quick Track 14',
    address: '701 NE Alsbury Blvd., Burleson, TX, 76028',
    lat: 32.562917,
    lng: -97.325954,
    phone: '',
    hours: 'Call to confirm',
    city: 'Burleson',
    state: 'TX',
    zip: '76028',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 28,
    name: 'Quick Track 16',
    address: '4624 E. FM 1187 Rd, Burleson, TX, 76028',
    lat: 32.57925,
    lng: -97.26306,
    phone: '',
    hours: 'Call to confirm',
    city: 'Burleson',
    state: 'TX',
    zip: '76028',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 29,
    name: 'Quick Track 44',
    address: '209 North Main St, Calvert, TX, 77837',
    lat: 30.981916,
    lng: -96.677118,
    phone: '',
    hours: 'Call to confirm',
    city: 'Calvert',
    state: 'TX',
    zip: '77837',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 30,
    name: 'Quick Track 17',
    address: '906 W. Main, Clarksville, TX, 75426',
    lat: 33.61004,
    lng: -95.056564,
    phone: '',
    hours: 'Call to confirm',
    city: 'Clarksville',
    state: 'TX',
    zip: '75426',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 31,
    name: 'Quick Track 19',
    address: '909 W Main st, Clarksville, TX, 75426',
    lat: 33.6104,
    lng: -95.05657,
    phone: '',
    hours: 'Call to confirm',
    city: 'Clarksville',
    state: 'TX',
    zip: '75426',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 32,
    name: 'Subway',
    address: '906 W. Main,Clarksville, TX 75426',
    lat: 33.609861,
    lng: -95.056669,
    phone: '',
    hours: 'Call to confirm',
    city: 'Clarksville',
    state: 'TX',
    zip: '75426',
    category: 'qt store',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 33,
    name: 'Quick Track 6',
    address: '2004 Live Oak St, Commerce, TX, 75428',
    lat: 33.247548,
    lng: -95.909258,
    phone: '',
    hours: 'Call to confirm',
    city: 'Commerce',
    state: 'TX',
    zip: '75428',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 34,
    name: 'Quick Track 52',
    address: '102 W. Highway 190, Copperas Cove, TX, 76522',
    lat: 31.11502,
    lng: -97.90611,
    phone: '',
    hours: 'Call to confirm',
    city: 'Copperas Cove',
    state: 'TX',
    zip: '76522',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 35,
    name: 'Quick Track 54',
    address: '1451 W. 2nd Avenue, Corsicana, TX, 75110',
    lat: 32.08947,
    lng: -96.48111,
    phone: '903-872-4125',
    hours: 'Call to confirm',
    city: 'Corsicana',
    state: 'TX',
    zip: '75110',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 36,
    name: 'Quick Track 55',
    address: '1139 W. 7th Avenue, Corsicana, TX, 75110',
    lat: 32.08629,
    lng: -96.47352,
    phone: '',
    hours: 'Call to confirm',
    city: 'Corsicana',
    state: 'TX',
    zip: '75110',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 37,
    name: 'QT 41B',
    address: '360 NW Front St, De Kalb, TX 75559',
    lat: 33.51041910000001,
    lng: -94.61939500000001,
    phone: '',
    hours: 'Call to confirm',
    city: 'De Kalb',
    state: 'TX',
    zip: '75559',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 38,
    name: 'Quick Track 41',
    address: '360 NW Front Street, Dekalb, TX, 75559',
    lat: 33.510419,
    lng: -94.619395,
    phone: '',
    hours: 'Call to confirm',
    city: 'Dekalb',
    state: 'TX',
    zip: '75559',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 39,
    name: 'Quick Track 32',
    address: '186 US Hwy 271 S, Deport, TX, 75434',
    lat: 33.527442,
    lng: -95.325768,
    phone: '',
    hours: 'Call to confirm',
    city: 'Deport',
    state: 'TX',
    zip: '75434',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 40,
    name: 'Lackland Plaza',
    address: '3123 Lackland Rd, Fort Worth, TX 76116',
    lat: 32.7284713,
    lng: -97.4343938,
    phone: '',
    hours: 'Call to confirm',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76116',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 41,
    name: 'Quick Track 36',
    address: '700 N Riverside Dr, Fort Worth, TX, 76111',
    lat: 32.773681,
    lng: -97.301297,
    phone: '',
    hours: 'Call to confirm',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76111',
    category: 'c-store',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 42,
    name: 'Quick Track 4',
    address: '4920 Bryant Irvin Rd, Fort Worth, TX, 76132',
    lat: 32.677805,
    lng: -97.416563,
    phone: '',
    hours: 'Call to confirm',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76132',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 43,
    name: 'Quick Track 5',
    address: '801 E. Allen Ave, Fort Worth, TX, 76104',
    lat: 32.726376,
    lng: -97.319737,
    phone: '',
    hours: 'Call to confirm',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76104',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 44,
    name: 'Quick Track 7',
    address: '1934 N. Interstate 35, Gainesville, TX, 76240',
    lat: 33.646293,
    lng: -97.154883,
    phone: '',
    hours: 'Call to confirm',
    city: 'Gainesville',
    state: 'TX',
    zip: '76240',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 45,
    name: 'Quick Track 42',
    address: '8966 US Hwy 271 N, Gilmer, TX, 75644',
    lat: 32.857275,
    lng: -94.95108,
    phone: '',
    hours: 'Call to confirm',
    city: 'Gilmer',
    state: 'TX',
    zip: '75644',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 46,
    name: 'LP Food Mart',
    address: '609 Bellaire Dr, Hurst, TX, 76053',
    lat: 32.820011,
    lng: -97.160178,
    phone: '',
    hours: 'Call to confirm',
    city: 'Hurst',
    state: 'TX',
    zip: '76053',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 47,
    name: 'Quick Track 48',
    address: '708 Frontage Rd, Idalou, TX',
    lat: 33.66415,
    lng: -101.68897,
    phone: '',
    hours: 'Call to confirm',
    city: 'Idalou',
    state: 'TX',
    zip: '',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 48,
    name: 'Quick Track 37',
    address: '1701 Henderson Blvd, Kilgore, TX, 75662',
    lat: 32.373183,
    lng: -94.869609,
    phone: '',
    hours: 'Call to confirm',
    city: 'Kilgore',
    state: 'TX',
    zip: '75662',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 49,
    name: 'Quick Track 53',
    address: '1401 S. Key Ave, Lampasas, TX, 76550',
    lat: 31.05606,
    lng: -98.17826,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lampasas',
    state: 'TX',
    zip: '76550',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 50,
    name: 'Quick Track 65',
    address: '3402 98th St., Lubbock, TX, 79423',
    lat: 33.50569,
    lng: -101.88821,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lubbock',
    state: 'TX',
    zip: '79423',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 51,
    name: 'Quick Track 66',
    address: '5746 82nd Frankford Ave., Lubbock, TX, 79423',
    lat: 33.51976,
    lng: -101.93972,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lubbock',
    state: 'TX',
    zip: '79423',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 52,
    name: 'Quick Track 67',
    address: '8109 Indiana, Lubbock, TX, 79423',
    lat: 33.52016,
    lng: -101.88723,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lubbock',
    state: 'TX',
    zip: '79423',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 53,
    name: 'Quick Track 68',
    address: '2318 W. 19th, Lubbock, TX, 79401',
    lat: 33.57813,
    lng: -101.86711,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lubbock',
    state: 'TX',
    zip: '79401',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 54,
    name: 'Quick Track 69',
    address: '2102 50th, Lubbock, TX, 79412',
    lat: 33.54911,
    lng: -101.8621,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lubbock',
    state: 'TX',
    zip: '79412',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 55,
    name: 'Quick Track 70',
    address: '802 Avenue Q, Lubbock, TX, 76401',
    lat: 33.58807,
    lng: -101.85563,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lubbock',
    state: 'TX',
    zip: '76401',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 56,
    name: 'Quick Track 71',
    address: '2504 98th St., Lubbock, TX, 79421',
    lat: 33.50617,
    lng: -101.87115,
    phone: '',
    hours: 'Call to confirm',
    city: 'Lubbock',
    state: 'TX',
    zip: '79421',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 57,
    name: 'Victory Dr.',
    address: '2606 Victory Dr, Marshall, TX 75672',
    lat: 32.5448263,
    lng: -94.33823079999999,
    phone: '',
    hours: 'Call to confirm',
    city: 'Marshall',
    state: 'TX',
    zip: '75672',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 58,
    name: 'Quick Track 61',
    address: '509 W. Mc Gregor Drive, TX, 76657',
    lat: 31.44378,
    lng: -97.41132,
    phone: '',
    hours: 'Call to confirm',
    city: 'Mc Gregor',
    state: 'TX',
    zip: '76657',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 59,
    name: 'Quick Track 8',
    address: '501 N. Galloway, Mequite, TX, 75149',
    lat: 32.771069,
    lng: -96.599517,
    phone: '972-289-6235',
    hours: 'Call to confirm',
    city: 'Mequite',
    state: 'TX',
    zip: '75149',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 60,
    name: 'Quick Track 81',
    address: '4324 Andrews Hwy, Midland, TX, 79703',
    lat: 32.00237,
    lng: -102.13648,
    phone: '',
    hours: 'Call to confirm',
    city: 'Midland',
    state: 'TX',
    zip: '79703',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 61,
    name: 'Quick Track 82',
    address: '4401 W. Illinois St., Midland, TX, 79703',
    lat: 31.98879,
    lng: -102.12814,
    phone: '432-694-9841',
    hours: 'Call to confirm',
    city: 'Midland',
    state: 'TX',
    zip: '79703',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 62,
    name: 'Quick Track 73',
    address: '2455 Kermit Highway, Odessa, TX, 79761',
    lat: 31.86398,
    lng: -102.38768,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79761',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 63,
    name: 'Quick Track 74',
    address: '4121 N. County Rd. W, Odessa, TX, 79764',
    lat: 31.87826,
    lng: -102.40192,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79764',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 64,
    name: 'Quick Track 75',
    address: '800 N. Grandview, Odessa, TX, 79761',
    lat: 31.86148,
    lng: -102.34571,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79761',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 65,
    name: 'Quick Track 76',
    address: '4525 E. University, Odessa, TX, 79764',
    lat: 31.87941,
    lng: -102.33175,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79764',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 66,
    name: 'Quick Track 77',
    address: '1509 FM 1936, Odessa, TX, 79764',
    lat: 31.87724,
    lng: -102.45431,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79764',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 67,
    name: 'Quick Track 78',
    address: '13920 W. Highway 80 E, Odessa, TX, 79765',
    lat: 31.89553,
    lng: -102.27049,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79765',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 68,
    name: 'Quick Track 79',
    address: '801 N. Golder Ave., Odessa, TX, 79764',
    lat: 31.88934,
    lng: -102.39589,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79764',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 69,
    name: 'Quick Track 80',
    address: '1523 N. HArless Ave, Odessa, TX, 79761',
    lat: 31.84785,
    lng: -102.40321,
    phone: '',
    hours: 'Call to confirm',
    city: 'Odessa',
    state: 'TX',
    zip: '79761',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 70,
    name: 'Quick Track 38',
    address: '201 S Commerce, Overton, TX, 75684',
    lat: 32.273844,
    lng: -94.978561,
    phone: '',
    hours: 'Call to confirm',
    city: 'Overton',
    state: 'TX',
    zip: '75684',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 71,
    name: 'Quick Track 40',
    address: '1001 S Commerce, Overton, TX, 75684',
    lat: 32.267347,
    lng: -94.980022,
    phone: '',
    hours: 'Call to confirm',
    city: 'Overton',
    state: 'TX',
    zip: '75684',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 72,
    name: 'Quick Track 21',
    address: '1604 N Main St., Paris, TX, 75460',
    lat: 33.67675,
    lng: -95.55543,
    phone: '903-737-8600',
    hours: 'Call to confirm',
    city: 'Paris',
    state: 'TX',
    zip: '75460',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 73,
    name: 'Quick Track 25',
    address: '663 Bonham Street, Paris, TX, 75460',
    lat: 33.66112,
    lng: -95.562835,
    phone: '',
    hours: 'Call to confirm',
    city: 'Paris',
    state: 'TX',
    zip: '75460',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 74,
    name: 'Quick Track 26',
    address: '3751 Lamar Ave, Paris, TX, 75460',
    lat: 33.662351,
    lng: -95.508035,
    phone: '',
    hours: 'Call to confirm',
    city: 'Paris',
    state: 'TX',
    zip: '75460',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 75,
    name: 'Quick Track 27',
    address: '2717 Lamr Ave, Paris, TX, 75460',
    lat: 33.660995,
    lng: -95.526379,
    phone: '',
    hours: 'Call to confirm',
    city: 'Paris',
    state: 'TX',
    zip: '75460',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 76,
    name: 'Quick Track 30',
    address: '704 Bonham Street, Paris, TX, 75460',
    lat: 33.661571,
    lng: -95.563254,
    phone: '',
    hours: 'Call to confirm',
    city: 'Paris',
    state: 'TX',
    zip: '75460',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 77,
    name: 'Quick Track 11',
    address: '310 Fulton St., Pitsburg, TX, 75686',
    lat: 32.992297,
    lng: -94.973604,
    phone: '',
    hours: 'Call to confirm',
    city: 'Pitsburg',
    state: 'TX',
    zip: '75686',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 78,
    name: 'Quick Track 22',
    address: '403 S Greer Blvd, Pitsburg, TX, 75686',
    lat: 32.99152,
    lng: -94.963021,
    phone: '',
    hours: 'Call to confirm',
    city: 'Pitsburg',
    state: 'TX',
    zip: '75686',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 79,
    name: 'Quick Track 24',
    address: '6404 US Hwy 271 N, Powderly, TX, 75473',
    lat: 33.782405,
    lng: -95.53327,
    phone: '',
    hours: 'Call to confirm',
    city: 'Powderly',
    state: 'TX',
    zip: '75473',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 80,
    name: 'Quick Track 9',
    address: '926 E. 130, Royse City, TX, 75189',
    lat: 29.801365,
    lng: -95.212004,
    phone: '',
    hours: 'Call to confirm',
    city: 'Royse City',
    state: 'TX',
    zip: '75189',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 81,
    name: 'Quick Track 12',
    address: '1321 S Broadway, Sulphur Springs, TX, 75482',
    lat: 33.115293,
    lng: -95.596932,
    phone: '',
    hours: 'Call to confirm',
    city: 'Sulphur Springs',
    state: 'TX',
    zip: '75482',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 82,
    name: 'Quick Track 45',
    address: '1320 Mockingbird Lane, Sulphur Springs, TX',
    lat: 33.11454,
    lng: -95.59211,
    phone: '',
    hours: 'Call to confirm',
    city: 'Sulphur Springs',
    state: 'TX',
    zip: '',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 83,
    name: 'Quick Track 23',
    address: '500 S 1st St, Hwy 271, Talco, TX, 75487',
    lat: 33.362613,
    lng: -95.104664,
    phone: '',
    hours: 'Call to confirm',
    city: 'Talco',
    state: 'TX',
    zip: '75487',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 84,
    name: 'Quick Track 56',
    address: '4200 West Waco Drive, TX, 76710',
    lat: 31.52948,
    lng: -97.16891,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76710',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 85,
    name: 'Quick Track 57',
    address: '1800 Lyle Avenue, Waco, TX, 76708',
    lat: 31.56744,
    lng: -97.16229,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76708',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 86,
    name: 'Quick Track 58',
    address: '825 W. Waco Drive, TX, 76707',
    lat: 31.55818,
    lng: -97.14034,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76707',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 87,
    name: 'Quick Track 59',
    address: '2429 W Waco Drive, TX, 76707',
    lat: 31.54336,
    lng: -97.15308,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76707',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 88,
    name: 'Quick Track 60',
    address: '3225 Hillcrest Drive, Waco, TX, 76708',
    lat: 31.55788,
    lng: -97.17862,
    phone: '254-753-4221',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76708',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: true,
    addressComplete: true,
  },
  {
    id: 89,
    name: 'Quick Track 62',
    address: '300 La Salle Avenue, Waco, TX, 76706',
    lat: 31.54167,
    lng: -97.11057,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76706',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 90,
    name: 'Quick Track 63',
    address: '4716 Bosque Blvd, Waco, TX, 76710',
    lat: 31.53562,
    lng: -97.18712,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76710',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 91,
    name: 'Quick Track 64',
    address: '6800 Sanger Avenue, Waco, TX, 76710',
    lat: 31.51906,
    lng: -97.19911,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76710',
    category: 'c-store+ gas+rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 92,
    name: 'Quick Track 72',
    address: '2909 Robinson Dr., Waco, TX, 79706',
    lat: 31.5124,
    lng: -97.12894,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '79706',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 93,
    name: 'Sanger Complex',
    address: '6808 Sanger Avenue, Waco, TX, 76711',
    lat: 31.5193313,
    lng: -97.1993452,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76711',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 94,
    name: 'Sanger Complex',
    address: '6816 Sanger Avenue, Waco, TX, 76711',
    lat: 31.5191616,
    lng: -97.19934980000001,
    phone: '',
    hours: 'Call to confirm',
    city: 'Waco',
    state: 'TX',
    zip: '76711',
    category: 'c-store +rental',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 95,
    name: 'Quick Track 28',
    address: '2101 Clear Lake Rd, Weatherford, TX, 76087',
    lat: 32.73715,
    lng: -97.76078,
    phone: '',
    hours: 'Call to confirm',
    city: 'Weatherford',
    state: 'TX',
    zip: '76087',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },
  {
    id: 96,
    name: 'Quick Track 47',
    address: '2601 Zion Hill Rd, Weatherford, TX',
    lat: 32.81028,
    lng: -97.82429,
    phone: '',
    hours: 'Call to confirm',
    city: 'Weatherford',
    state: 'TX',
    zip: '',
    category: 'c-store + gas',
    hoursVerified: false,
    phoneVerified: false,
    addressComplete: true,
  },

];

/** Look up one store by id. */
export function getStoreById(id: number): Store | undefined {
  return stores.find((store) => store.id === id);
}

/** All stores, in stable state/city/name order. */
export function getAllStores(): Store[] {
  return stores;
}

/** Stores whose hours are still placeholder. Should reach zero. */
export function getStoresNeedingHours(): Store[] {
  return stores.filter((s) => !s.hoursVerified);
}

/** Stores whose address has no street number. Should reach zero. */
export function getStoresNeedingAddress(): Store[] {
  return stores.filter((s) => s.addressComplete === false);
}

/** Stores with no phone number recovered. Should reach zero. */
export function getStoresNeedingPhone(): Store[] {
  return stores.filter((s) => !s.phoneVerified);
}
